version: '3'
services:
  web:
    container_name: nabootsocket-web
    build:
      context: .
      dockerfile: web-dockerfile
    working_dir: /web
    ports:
      - 9001:9001
    depends_on:
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=prod
  mysql:
    container_name: nabootsocket-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: nabootsocket
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp