spring:
  datasource:
    url: jdbc:mysql://mysql-socket:3306/nabootsocket?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: nabootsocket

authserver:
  url: http://web-auth:9000

appserver:
  url: "*"

webserver:
  url: http://web-service:8080